services:
  - type: worker
    name: damodar-tech-empire-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./run_forever.sh
    envVars:
      - key: PYTHON_VERSION
      - value: 3.10.0
